"""teste2.

Revision ID: 766d6e518f88
Revises: 
Create Date: 2025-08-12 09:30:54.270714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766d6e518f88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ufs',
    sa.Column('CO_UF', sa.Integer(), nullable=False),
    sa.Column('SG_UF', sa.String(length=2), nullable=False),
    sa.Column('NO_UF', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('CO_UF')
    )
    op.create_table('mesorregioes',
    sa.Column('CO_MESORREGIAO', sa.Integer(), nullable=False),
    sa.Column('NO_MESORREGIAO', sa.Text(), nullable=False),
    sa.Column('CO_UF', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CO_UF'], ['ufs.CO_UF'], ),
    sa.PrimaryKeyConstraint('CO_MESORREGIAO')
    )
    op.create_table('microrregioes',
    sa.Column('CO_MICRORREGIAO', sa.Integer(), nullable=False),
    sa.Column('NO_MICRORREGIAO', sa.Text(), nullable=False),
    sa.Column('CO_MESORREGIAO', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CO_MESORREGIAO'], ['mesorregioes.CO_MESORREGIAO'], ),
    sa.PrimaryKeyConstraint('CO_MICRORREGIAO')
    )
    op.create_table('municipios',
    sa.Column('CO_MUNICIPIO', sa.Integer(), nullable=False),
    sa.Column('NO_MUNICIPIO', sa.Text(), nullable=False),
    sa.Column('CO_MICRORREGIAO', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CO_MICRORREGIAO'], ['microrregioes.CO_MICRORREGIAO'], ),
    sa.PrimaryKeyConstraint('CO_MUNICIPIO')
    )
    op.create_table('instituicoes',
    sa.Column('NU_ANO_CENSO', sa.Integer(), nullable=False),
    sa.Column('CO_ENTIDADE', sa.Integer(), nullable=False),
    sa.Column('NO_REGIAO', sa.String(), nullable=False),
    sa.Column('CO_REGIAO', sa.Integer(), nullable=False),
    sa.Column('NO_UF', sa.String(), nullable=False),
    sa.Column('SG_UF', sa.String(), nullable=False),
    sa.Column('CO_UF', sa.Integer(), nullable=False),
    sa.Column('NO_MUNICIPIO', sa.String(), nullable=False),
    sa.Column('CO_MUNICIPIO', sa.Integer(), nullable=False),
    sa.Column('CO_MESORREGIAO', sa.Integer(), nullable=False),
    sa.Column('CO_MICRORREGIAO', sa.Integer(), nullable=False),
    sa.Column('NO_ENTIDADE', sa.String(), nullable=False),
    sa.Column('QT_MAT_BAS', sa.Integer(), nullable=False),
    sa.Column('QT_MAT_EJA', sa.Integer(), nullable=False),
    sa.Column('QT_MAT_ESP', sa.Integer(), nullable=False),
    sa.Column('QT_MAT_FUND', sa.Integer(), nullable=False),
    sa.Column('QT_MAT_INF', sa.Integer(), nullable=False),
    sa.Column('QT_MAT_MED', sa.Integer(), nullable=False),
    sa.Column('QT_MAT_PROF', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CO_MESORREGIAO'], ['mesorregioes.CO_MESORREGIAO'], ),
    sa.ForeignKeyConstraint(['CO_MICRORREGIAO'], ['microrregioes.CO_MICRORREGIAO'], ),
    sa.ForeignKeyConstraint(['CO_MUNICIPIO'], ['municipios.CO_MUNICIPIO'], ),
    sa.ForeignKeyConstraint(['CO_UF'], ['ufs.CO_UF'], ),
    sa.PrimaryKeyConstraint('NU_ANO_CENSO', 'CO_ENTIDADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instituicoes')
    op.drop_table('municipios')
    op.drop_table('microrregioes')
    op.drop_table('mesorregioes')
    op.drop_table('ufs')
    # ### end Alembic commands ###
